apiVersion: apps/v1
kind: Deployment
metadata:
  name: slo-alerting-demo-eployment
  labels:
    app: slo-alerting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slo-alerting-demo
  template:
    metadata:
      labels:
        app: slo-alerting-demo
    spec:
      containers:
      - name: slo-alerting-demo-server
        image: gcr.io/stack-doctor/slo-alerting-demo:latest
        ports:
        - containerPort: 8080
        env:
          # Define the environment variable
          - name: ERROR_RATE
            valueFrom:
              configMapKeyRef:
                name: error-rate
                key: ERROR_RATE